### ISSUE TITLE
Thingiverse objects not displayed

### ISSUE THREAD

**Issue by mot-liw** [appdevelopmentandsuch/MMM-Thingiverse#5]
The MMM-Thingiverse module on my system is not displaying the items from Thingiverse, I am not certain why. 
The Pi 4b is running MM2 v2.14.0 and MMM-Thingiverse v1.1.1.
I am debugging with server only mode; in the browsers debug window it shows that the info/data from Thingiverse is being received, but it is not being displayed; I have also run MM2 in standard mode and no Thingiverse objects are displayed.
I have tested to insure my Thingiverse appKey is valid, as well as the browser debug data shows Thingiverse objects being received. 

Server startup messages:
~/MagicMirror $ npm run server

> magicmirror@2.14.0 server
> node ./serveronly

[30.03.2021 07:53.50.602] [LOG]   Starting MagicMirror: v2.14.0
[30.03.2021 07:53.50.612] [LOG]   Loading config ...
[30.03.2021 07:53.50.618] [LOG]   Loading module helpers ...
[30.03.2021 07:53.50.623] [LOG]   No helper found for module: clock.
[30.03.2021 07:53.50.626] [LOG]   No helper found for module: MMMM-Thingiverse.
[30.03.2021 07:53.50.627] [LOG]   All module helpers loaded.
[30.03.2021 07:53.50.725] [LOG]   Starting server on port 8080 ... 
[30.03.2021 07:53.50.747] [LOG]   Server started ...
[30.03.2021 07:53.50.748] [LOG]   Sockets connected & modules started ...
[30.03.2021 07:53.50.748] [LOG]   
Ready to go! Please point your browser to: http://localhost:8080
^C[30.03.2021 08:02.23.439] [LOG]   [SIGINT] Received. Shutting down server...

Do you have any ideas  why my system is not displaying the Thingiverse objects?

The config file attached is one that I removed all my other modules from, to check if there were some problem with other modules blocking things from being displayed.
	modules: [
		{
			module: "clock",
			position: "top_center"
		},
		{
			module: 'MMMM-Thingiverse',
			config: {
				appToken: '######################################',
				//updateinterval: 60*60*1000,
				//thingCount: 50,
				//numThingsDisplayed: 5,
			},
		},	
	]

The attached screen shot shows the browser display and that Thingiverse objects are being received by the browser.
![Screenshot from 2021-03-30 08-18-27](https://user-images.githubusercontent.com/65913216/113006649-cb4ac780-9132-11eb-9844-e88aa166a84a.png)
[myconfig.js.gz](https://github.com/appdevelopmentandsuch/MMM-Thingiverse/files/6229781/myconfig.js.gz)

**Comment by bocklucas** [comment]
@mot-liw hmmmm this is very peculiar...

While you have dev tools open, can you see if the elements are being created properly in the html element inspector?

**Comment by mot-liw** [comment]
answers in reverse
the config is using the default update interval at this time, which looks to be 60000 (every 60 seconds)

I see this in the element inspector
<script type="text/javascript" src="modules/MMM-Thingiverse//MMM-Thingiverse.js"></script>

I am not certain if this is what you are asking about to determine if the element is being properly created?
There is an odd '//' in the path, at least it's odd to me.

This is from the Element>Console
Translations loaded for: clock
loader.js:176 Load script: modules/MMM-Thingiverse//MMM-Thingiverse.js
module.js:509 Check MagicMirror version for module 'MMM-Thingiverse' - Minimum version:  2.1.0 - Current version: 2.14.0
module.js:511 Version is ok!
module.js:517 Module registered: MMM-Thingiverse
loader.js:148 Bootstrapping module: MMM-Thingiverse
loader.js:153 Scripts loaded for: MMM-Thingiverse
loader.js:195 Load stylesheet: modules/MMM-Thingiverse/MMM-Thingiverse.css
loader.js:155 Styles loaded for: MMM-Thingiverse
translator.js:110 MMM-Thingiverse - Load translation fallback: translations/en.json
loader.js:157 Translations loaded for: MMM-Thingiverse
loader.js:195 Load stylesheet: css/custom.css
clock.js:46

**Comment by bocklucas** [comment]
@mot-liw Hmmm I'm running MagicMirror V2.14 on my Ubuntu 20.04 Laptop.

Sorry, I was referring to this, are you able to see the HTML elements in the `Element` tab of the Dev Tools? 
![Screenshot from 2021-03-30 21-06-09](https://user-images.githubusercontent.com/22528729/113080019-c66e2e00-919b-11eb-9af0-ecd740e0b3fd.png)

This will help me determine whether or not the elements are being created.

**Comment by mot-liw** [comment]
Gotcha, it looks like they are not, I see no elements in the bottom bar container class. 
![Screenshot from 2021-03-30 20-12-54](https://user-images.githubusercontent.com/65913216/113080822-c0288380-9194-11eb-838a-af1677d335b4.png)

**Comment by bocklucas** [comment]
@mot-liw i could be missing something but did you assign a position to the module? I don't see it in your initial comment config

**Comment by mot-liw** [comment]
I did not assign a position, I did not see the position attribute specified in the module's readme, so I thought that it was defaulting to the bottom bar. In my config I have commented out all module attributes except the appKey, trying to keep it simple. I see no errors in the console log that would indicate that it is unhappy with something.

**Comment by bocklucas** [comment]
@mot-liw ahh this is fair! I will update the readme to be more explicit. 

If you assign it a position like so

```
modules: [
{
module: "clock",
position: "top_center"
},
{
module: 'MMMM-Thingiverse',
position: "bottom_bar",
config: {
appToken: '######################################',
//updateinterval: 60601000,
//thingCount: 50,
//numThingsDisplayed: 5,
},
},
]
```

Do you see the Thingiverse objects now?

**Comment by mot-liw** [comment]
Oh yea!, yes the fact that I had not provided a position was the issue, aka a skinware issue, I should have considered the position. Yes, a documentation update would be beneficial.
thx for your assistance
This project is for the Future Forge makerspace in Silver City, NM; if you are ever in the area (remotely possible;)) stop in.
![Screenshot from 2021-03-31 07-32-12](https://user-images.githubusercontent.com/65913216/113152731-a407ff00-91f3-11eb-8951-0d04e17ad020.png)

**Comment by bocklucas** [comment]
@mot-liw awesome! Oh for sure!!
