### ISSUE TITLE
Correction to "ReadMe" -> "Using the module" ->  module: 'MMMM-Thingiverse', should display module: 'MMM-Thingiverse',

### ISSUE THREAD

**Issue by unlikelytheory** [appdevelopmentandsuch/MMM-Thingiverse#6]
Apologies in advance, I'm a beginner and had some issues setting up the module. I noticed in the README configuration that the module: 'MMMM-Thingiverse', was not returning results. Corrected it to 'MMM-Thingiverse' and your module is working flawlessly for me now. Just thought it drop a quick correction, if needed. (Again very new to this side of tech, and not sure if MMMM was meant.) Thanks!

**Comment by bocklucas** [comment]
Wow man i goofed that pretty hard!

Thanks for the heads up @unlikelytheory !!
I'll be sure to fix the Readme, much appreciated!!

That was not intentional lol, very excellent catch

**Comment by bocklucas** [comment]
Thanks again @unlikelytheory !!
